version: "3"
services:
  web:
    image: dockermaker
    volumes:
      - ./client:/usr/src/app/client
      - ./public:/usr/src/app/public
      - ./server:/usr/src/app/server
    ports:
      - "3000:3000"
    networks:
      - webnet
    depends_on:
      - db
    environment:
      SESSION_SECRET: "your session secret"
      NODE_ENV: development
      DATABASE_URL: postgres://postgres@db:5432/dockermaker
      PORT: 3000
  db:
    image: postgres:9.6
    ports:
      - "5433:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: dockermaker
    networks:
      - webnet
networks:
  webnet:
